app:
  host: 127.0.0.1
  port: 8000
  # API will auto-reload when changes on code files are detected
  reload: true
images:
  image_thumbnail_size: [50, 50]
  waveform_thumbnail_size: [100, 100]
  default_colour_map: viridis
  colourbar_height_pixels: 16
  upload_image_threads: 4
  preferred_colour_map_pref_name: PREFERRED_COLOUR_MAP
echo:
  url: http://127.0.0.1:9000
  username: operationsgateway
  access_key: minioadmin
  secret_key: minioadmin
  bucket_name: og-actions-test
mongodb:
  mongodb_url: mongodb://localhost:27017
  database_name: opsgateway
  # Maximum number of documents to return when querying, similar to ICAT's maxEntities
  max_documents: 1000
auth:
  private_key_path: /home/runner/work/operationsgateway/id_rsa
  public_key_path: /home/runner/work/operationsgateway/id_rsa.pub
  jwt_algorithm: RS256
  access_token_validity_mins: 180
  refresh_token_validity_days: 7
  fedid_server_url: ldap://fed.cclrc.ac.uk:389
  fedid_server_ldap_realm: FED.CCLRC.AC.UK
experiments:
  user_office_wsdl_url: https://devapi.facilities.rl.ac.uk/ws/UserOfficeWebService?wsdl
  scheduler_wsdl_url: https://devapis.facilities.rl.ac.uk/ws/ScheduleWebService?wsdl
  # Credentials for user office/scheduler system
  username: username
  password: password
  # When no experiments are stored in the database, this is the start date to use when
  # contacting the Scheduler for the 'new experiments'. This setting is only used the
  # first time that experiments are being populated into the database
  first_scheduler_contact_start_date: 2019-01-02T00:00:00Z
  # Flag to enable/disable the background task to contact the Scheduler
  scheduler_background_task_enabled: false
  # Cron job string format. Every Monday at 9:00am - 0 9 * * 1
  scheduler_background_frequency: 0 9 * * 1
  # Timezones as per dateutil.tz. https://stackoverflow.com/a/15454186 provides a way of
  # listing available timezones
  scheduler_background_timezone: Europe/London
  # Number of minutes to wait before retrying if the background task of getting new
  # experiments from the Scheduler fails
  scheduler_background_retry_mins: 20
  instrument_names:
    - Gemini
  worker_file_path: /dev/shm/og-experiment-background
export:
  # 1048576 = 1 MB
  # 1073741824 = 1 GB
  max_filesize_bytes: 1073741824