script_options:
  wipe_database: false
  wipe_echo: false
  launch_api: true
  import_users: true
ssh:
  enabled: false
  ssh_connection_url: 127.0.0.1
database:
  hostname: localhost
  port: 27017
  name: opsgateway
  remote_experiments_file_path: /tmp/experiments_for_mongoimport.json
  test_users_file_path: util/users_for_mongoimport.json
echo:
  endpoint_url: https://s3.echo.stfc.ac.uk
  access_key: access_key
  secret_key: secret_key
  simulated_data_bucket: og-ci-simulated-data
  storage_bucket: og-bucket
  page_size: 400
api:
  https: false
  host: 127.0.0.1
  port: 8000
  username: backend
  password: back
  log_config_path: /home/runner/work/operationsgateway/operationsgateway-api/operationsgateway_api/logging.ini
  gunicorn_num_workers: "1"
  timeout_seconds: 1000
